version: '3.8'
services:

  web:
    container_name: web
    build: .
    environment:
      - PORT=8000
    command: sh -c "gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    
  redis:
    image: "redis:alpine"

  celery_worker:
    build: .
    command: celery -A src.tasks.celery_config worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_beat:
    build: .
    command:  celery -A src.tasks.celery_config beat 
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis


